### ISSUE TITLE
Support rusty-dark-syntax

### ISSUE THREAD

**Issue by cbruun** [miqid/atom-language-rust#4]
The [rusty-dark-syntax](https://github.com/Nercury/atom-rusty-dark-syntax) theme has the following in its README:

> There is a new package atom-language-rust (not to be mistaken with language-rust) that changes styles defined by language-rust and even forces specific colors for these styles, preventing theme authors from creating themes for Rust.

Basically it is not possible to use rusty-dark-syntax with atom-language-rust and get the correct colors shown. Perhaps something can be done to fix this?

**Comment by miqid** [comment]
I've already pointed this out to the author of the `rusty-dark-syntax` package, but they've either misunderstood or ignored my suggestion on how to have the `atom-language-rust` package work along side of it.

If you don't want the `atom-language-rust` package to interfere by supplying any styles, simply ensure the _Additional Styles_ setting is unchecked. In case you don't know how to locate the settings of a package, details can be found on the [README](https://github.com/miqid/atom-language-rust/blob/ba2f4c6/README.md).

**Comment by cbruun** [comment]
I read the discussion and I agree with you. As the styles can be disabled, there is no issue.

I will open an issue on `rusty-dark-syntax` if find any grammar classes from `atom-language-rust` that is not applied a color.
