### ISSUE TITLE
Grammar doesn't recognise `where` clauses on new lines

### ISSUE THREAD

**Issue by hawkw** [miqid/atom-language-rust#6]
Oftentimes, when I have a long `where` clause in an `impl` block, I like to put the `where` on the next line after the `impl`. While the Rust style guide's [line wrapping](https://github.com/rust-lang/rust/blob/master/src/doc/style/style/whitespace.md#line-wrapping) section doesn't specifically mention `where` clauses, this is in line with the wrapping style for things like functions, and occurs pretty frequently in the standard library code, so I consider it good style when appropriate. 

However, the `atom-language-rust` grammar doesn't recognise `where` clauses beginning on the next line after an `impl` or `fn`. This throws off syntax highlighting for the `where` clause, and also usually for the next line after it, as well. 

Here are two screenshots demonstrating the difference:
<img width="480" alt="screen shot 2016-05-16 at 12 36 50 pm" src="https://cloud.githubusercontent.com/assets/2796466/15296495/9ba732a6-1b63-11e6-9e03-de7c759f3801.png">
<img width="490" alt="screen shot 2016-05-16 at 12 37 04 pm" src="https://cloud.githubusercontent.com/assets/2796466/15296496/9bb07db6-1b63-11e6-97ab-067fb83cf3f3.png">

I would have fixed this myself and submitted a pull request, but I'm not terribly familiar with how Atom grammars work. I'd be happy to work on fixing this issue if someone would be willing to give me some guidance.

**Comment by miqid** [comment]
Much obliged for pointing out this inconsistent matching behaviour for `where` clauses.

I've committed a fix that should address the `where` keyword not being recognised on new line following an `impl`, `fn`, `struct` or `trait`. It should be going into the next release (0.8.0), so please look forward to it then.

**Comment by hawkw** [comment]
Excellent! Thanks so much for the speedy fix.

**Comment by miqid** [comment]
@hawkw, a fix for this issue has been included in [0.8.0](https://github.com/miqid/atom-language-rust/releases/tag/0.8.0).

If you still encounter highlighting inconsistency with `where` clauses, please reopen this issue. Thanks again for your report!

**Comment by hawkw** [comment]
Highlighting looks correct now. Thank you!
