### ISSUE TITLE
Falsely detected macro if `if` condition starts with `!(`

### ISSUE THREAD

**Issue by MoritzKn** [miqid/atom-language-rust#7]
Code like this is falsely recognized as macro:
```
if !(a && b) {}
if !(n - 2) % 3 == 0 {}
```
And this results in wrong syntax highlighting:
![rust_macro_demo](https://cloud.githubusercontent.com/assets/10676525/16637771/91827eba-43e1-11e6-9058-cbb24b03912b.png)

**Comment by miqid** [comment]
Nice catch and thank you very much for the report.

I found that some other expressions involving keywords other than `if` were affected by the same underlying problem (`match` was one). The fix I've published to version [0.8.1](https://github.com/miqid/atom-language-rust/releases/tag/0.8.1) should resolve it, so simply update your package in Atom.

If you are still seeing the incorrect matching behaviour, please reopen this issue.
